CasadoCelso = {'nome_estabelecimento': 'Casa do Celso','endereco_address': 'Rua do Celso','endereco_city': 'Campo Grande','endereco_state': 'MS','endereco_zip': '79000000','telefone': '679856954','infraestrutura':  " ['Banheiro familiar', 'Monitor infantil', ''] " ,'adicionais':  " ['Acessibilidade', 'Estacionamento coberto', ''] " ,'aberturaH': '08','aberturaM': '00','fechaH': '16','fechaM': '15','menorMovH': '15','menorMovM': '00','descricao': 'Descricao do Celso'} 

CasadoRenato = {'nome_estabelecimento': 'Casa do Renato','endereco_address': 'rUA DO RENATO','endereco_city': '8494984','endereco_state': '8489','endereco_zip': '7899.5','telefone': '','infraestrutura':  " ['Banheiro familiar', 'Monitor infantil', ''] " ,'adicionais':  " ['Acessibilidade', 'Estacionamento coberto', ''] " ,'aberturaH': '08','aberturaM': '07','fechaH': '05','fechaM': '00','menorMovH': '15','menorMovM': '00','descricao': ''} 

FACÇÃOUFMS = {'nome_estabelecimento': 'FACÇÃO UFMS','endereco_address': 'UFMS','endereco_city': 'CAMPO GRANDE','endereco_state': 'MS','endereco_zip': '32342344234','telefone': '','infraestrutura':  " ['Banheiro familiar', 'Monitor infantil', ''] " ,'adicionais':  " ['Acessibilidade', 'Estacionamento coberto', ''] " ,'aberturaH': '08','aberturaM': '00','fechaH': '22','fechaM': '00','menorMovH': '17','menorMovM': '00','descricao': 'SEM DESCRIÇÃO'} 

SaleePepe = {'nome_estabelecimento': 'Sale e Pepe','endereco_address': 'rua 29 de maio 971','endereco_city': 'Bonito','endereco_state': 'MS','endereco_zip': '79290-000','telefone': '','infraestrutura':  " ['Banheiro familiar', 'Monitor infantil', ''] " ,'adicionais':  " ['Acessibilidade', 'Estacionamento coberto', ''] " ,'aberturaH': '08','aberturaM': '00','fechaH': '22','fechaM': '00','menorMovH': '16','menorMovM': '00','descricao': 'rodrigo'} 

Facao = {'nome_estabelecimento': 'Facao','endereco_address': '','endereco_city': '','endereco_state': '','endereco_zip': '','telefone': '','infraestrutura':  " ['Banheiro familiar', 'Microondas', ''] " ,'adicionais':  " ['Acessibilidade', 'Estacionamento coberto', ''] " ,'aberturaH': '08','aberturaM': '00','fechaH': '22','fechaM': '00','menorMovH': '15','menorMovM': '00','descricao': ''} 

